export const tabelas = {
  GV: `CREATE TABLE IF NOT EXISTS GV (
        id UUID PRIMARY KEY,
        nomeEmpresa TEXT,
        matricula TEXT,
        nome TEXT,
        cargos TEXT,
        dataAdmissao TIMESTAMP,
        area TEXT,
        salario FLOAT,
        sexo TEXT,
        cutis TEXT,
        dataNascimento TIMESTAMP,
        email TEXT,
        vinculoEmpregaticio TEXT,
        situacaoEmpregado TEXT,
        grauInstrucao TEXT,
        pcd BOOLEAN,
        desligado BOOLEAN,
        dataDesligamento TIMESTAMP,
        motivoDesligamento TEXT,
        tenant_id UUID,
      );`,
  // FUNCIONARIOS: `CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
  //       id UUID PRIMARY KEY,
  //       nomeEmpresa TEXT,
  //       matricula TEXT,
  //       nome TEXT,
  //       cargos TEXT,
  //       dataAdmissao TIMESTAMP,
  //       area TEXT,
  //       salario FLOAT,
  //       sexo TEXT,
  //       cutis TEXT,
  //       dataNascimento TIMESTAMP,
  //       email TEXT,
  //       vinculoEmpregaticio TEXT,
  //       situacaoEmpregado TEXT,
  //       grauInstrucao TEXT,
  //       pcd BOOLEAN,
  //       desligado BOOLEAN,
  //       dataDesligamento TIMESTAMP,
  //       motivoDesligamento TEXT,
  //       tenant_id UUID,
  //     );`,
};
